In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df=pd.read_csv("rainfall.csv")

In [19]:
df.head()

,Date,Location,Temperature,Humidity,Wind Speed,Precipitation,Cloud Cover,Pressure,Rain Tomorrow
0,2024-01-01,New York,87.524795,75.655455,28.379506,0.000000,69.617966,1026.030278,0
1,2024-01-02,New York,83.259325,28.712617,12.436433,0.526995,41.606048,995.962065,0
2,2024-01-03,New York,80.943050,64.740043,14.184831,0.916884,77.364763,980.796739,1
3,2024-01-04,New York,78.097552,59.738984,19.444029,0.094134,52.541196,979.012163,0
4,2024-01-05,New York,37.059963,34.766784,3.689661,1.361272,85.584000,1031.790859,0

In [11]:
df.shape

(73100, 9)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           73100 non-null  object
 1   Location       73100 non-null  object
 2   Temperature    73100 non-null  float64
 3   Humidity       73100 non-null  float64
 4   Wind Speed     73100 non-null  float64
 5   Precipitation  73100 non-null  float64
 6   Cloud Cover    73100 non-null  float64
 7   Pressure       73100 non-null  float64
 8   Rain Tomorrow  73100 non-null  int64
dtypes: float64(6), int64(1), object(2)
memory usage: 5.0+ MB

In [13]:
df.columns

Index(['Date', 'Location', 'Temperature', 'Humidity', 'Wind Speed',
       'Precipitation', 'Cloud Cover', 'Pressure', 'Rain Tomorrow'],
      dtype='object')

In [14]:
df.head()
df.shape
df.columns

Index(['Date', 'Location', 'Temperature', 'Humidity', 'Wind Speed',
       'Precipitation', 'Cloud Cover', 'Pressure', 'Rain Tomorrow'],
      dtype='object')

In [31]:
x=df[['Temperature', 'Humidity', 'Wind Speed',
       'Precipitation', 'Cloud Cover', 'Pressure']]
y=df['Rain Tomorrow']

In [32]:
x.head()

   Temperature   Humidity  Wind Speed  Precipitation  Cloud Cover     Pressure
0    87.524795  75.655455   28.379506       0.000000    69.617966  1026.030278
1    83.259325  28.712617   12.436433       0.526995    41.606048   995.962065
2    80.943050  64.740043   14.184831       0.916884    77.364763   980.796739
3    78.097552  59.738984   19.444029       0.094134    52.541196   979.012163
4    37.059963  34.766784    3.689661       1.361272    85.584000  1031.790859

In [33]:
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Rain Tomorrow, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
print("Training data:",x_train.shape)
print("Testing data:",x_test.shape)

Training data: (58480, 6)
Testing data: (14620, 6)

In [39]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [40]:
y_pred=model.predict(x_test)

In [43]:
y_pred[:10]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
accuracy=accuracy_score(y_test,y_pred)

In [47]:
print("Accuracy:",accuracy)

Accuracy: 0.909233926128591

In [52]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[10993   376]
 [  951  2300]]

In [53]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94     11369
           1       0.86      0.71      0.78      3251

    accuracy                           0.91     14620
   macro avg       0.89      0.84      0.86     14620
weighted avg       0.91      0.91      0.91     14620

In [56]:
#sample = [[30, 80, 10, 5, 70, 1010]]
#prediction = model.predict(sample)
#print("Rain Tomorrow:", prediction[0])

In [55]:
sample = pd.DataFrame([{'Temperature': 30,'Humidity': 80,'Wind Speed': 10,'Precipitation': 5,'Cloud Cover': 70,'Pressure': 1010 }])
prediction = model.predict(sample)
print("Rain Tomorrow:", prediction[0])

Rain Tomorrow: 1

In [57]:
import pickle
with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

In [58]:
import pickle
with open("model.pkl", "rb") as file:
    loaded_model = pickle.load(file)
print("Model loaded successfully!")

Model loaded successfully!